### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by ghost** [orf/spam#1]
Instructions could help non-techy users use the repo.

**Comment by orf** [comment]
Hey @DyingEcho, I was going to write a blog post about this and update the documentation. It's not finished yet however, I'll write something up soonish (tm)

**Comment by orf** [comment]
Hey, I have included an terminal recording and fixed up this, does this clear things up?

**Comment by ghost** [comment]
Ya, that would help. I'll also see if I can write some at some point.
